language: python
cache: pip
python:
    - "3.7"
env:
    -DJANGO=1.11.29 DB=postgresql
services:
  - postgresql
addons:
  ssh_known_hosts:
    - $SSH_IP
before_install:
  - sudo apt-get -y install libpq-dev libjpeg-dev
install:
    - pip install -r requirements.txt
    - mkdir logs
    - cp settings-travis.py settings.py
    - npm install newman@4.6.1
before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version
    - psql -c 'create database test_db;' -U postgres
    - python manage.py migrate
    - python manage.py loaddata fixtures/*.json
    - python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_user('asd', 'asd@asd.com', 'asd')"
    - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out /tmp/travis_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/travis_rsa
    - ssh-add /tmp/travis_rsa
    - scp -r $SSH_USER@SSH_IP:cache/ comprobante/
script:
    - python manage.py test
    - pylint anestesista/ caja/ comprobante/ estudio/ medico/ medicamento/ obra_social/ paciente/ practica/ presentacion/ sala/ scripts/ security/ turno/ usuario/
    - python manage.py runserver & node_modules/.bin/newman run integration_tests/cedir_web.postman_collection.json -e integration_tests/local.postman_environment.json --verbose
after_script:
    - scp -r comprobante/cache $SSH_USER@SSH_IP: