language: python
cache: pip
python:
        - "2.7"
env:
    -DJANGO=1.8 DB=msqlite3
install:
    - pip install -r requirements-travis.txt
    - mkdir logs
    - cp settings-travis.py settings.py
script:
    - python manage.py test
    - pylint caja/ comprobante/ estudio/ medico/ medicamento/ obra_social/ paciente/ practica/ presentacion/ sala/ scripts/ security/ turno/ usuario/