# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0008_auto_20200511_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='remito',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
