# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-13 11:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0008_auto_20200511_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='saldo_positivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
    ]
