# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-10 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from caja.models import MovimientoCaja, MontoAcumulado, TipoMovimientoCaja, ID_CONSULTORIO_1, ID_CONSULTORIO_2, ID_GENERAL

def crear_primeros_movimientos(apps, schema_editor):
    ultimo_mov = MovimientoCaja.objects.last()
    for tipo_id in (ID_GENERAL, ID_CONSULTORIO_1, ID_CONSULTORIO_2):
        tipo = TipoMovimientoCaja.objects.get(pk=tipo_id)
        MontoAcumulado.objects.create(tipo=tipo, monto_acumulado=0, movimiento=ultimo_mov)

class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20210419_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontoAcumulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.MovimientoCaja')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.TipoMovimientoCaja')),
            ],
            options={
                'db_table': 'tblMontoAcumulado',
            },
        ),
        migrations.RunPython(crear_primeros_movimientos),
    ]
